repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: ^tests/fixtures/
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    - id: black
      args: [--line-length=119]
      language_version: python3.10
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      verbose: true
# -   repo: local
#     hooks:
#       - id: pytest-check
#         name: pytest-check
#         entry: pytest
#         types: [python]
#         language: system
#         pass_filenames: false
#         always_run: true